version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.go
    environment:
      DB_URL: postgresql://app:app@postgres:5432/appdb
      JWT_SECRET: devjwtsecret_change_me
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"

volumes:
  pgdata:
