basePath: /
definitions:
  internal_http_handlers.AddWorkspaceMemberIn:
    properties:
      role:
        description: 役割（未指定は member）
        enum:
        - owner
        - member
        example: member
        type: string
      user_id:
        description: 追加するユーザのUUID
        example: 6d4c2f52-1f1c-4e7d-92a2-4b2d4a3d9a10
        type: string
    required:
    - user_id
    type: object
  internal_http_handlers.CreateChannelIn:
    properties:
      is_private:
        description: プライベートかどうか
        example: false
        type: boolean
      name:
        description: チャンネル名
        example: general
        type: string
    required:
    - name
    type: object
  internal_http_handlers.CreateWorkspaceIn:
    properties:
      name:
        description: ワークスペース名
        example: my-team
        type: string
    required:
    - name
    type: object
  internal_http_handlers.MemberCandidateRow:
    properties:
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
    type: object
  internal_http_handlers.MsgCreateIn:
    properties:
      parent_id:
        description: '追加: 返信先（UUID文字列）'
        type: string
      text:
        minLength: 1
        type: string
    required:
    - text
    type: object
  internal_http_handlers.MsgOut:
    properties:
      channel_id:
        type: string
      id:
        type: string
      parent_id:
        type: string
      text:
        type: string
      thread_root_id:
        type: string
      user_id:
        type: string
      workspace_id:
        type: string
    type: object
  internal_http_handlers.SignUpIn:
    properties:
      display_name:
        type: string
      email:
        type: string
      password:
        minLength: 4
        type: string
    required:
    - email
    - password
    type: object
  internal_http_handlers.TokenOut:
    properties:
      access_token:
        type: string
      token_type:
        type: string
    type: object
  internal_http_handlers.UserRow:
    properties:
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
    type: object
  internal_http_handlers.WorkspaceMemberRow:
    properties:
      display_name:
        example: Alice
        type: string
      email:
        example: alice@example.com
        type: string
      role:
        example: owner
        type: string
      user_id:
        example: 6d4c2f52-1f1c-4e7d-92a2-4b2d4a3d9a10
        type: string
    type: object
  slackgo_internal_model.Workspace:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: Minimal Slack-like backend with Gin + GORM + WS
  title: MySlack API (Go)
  version: "0.1"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.SignUpIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.TokenOut'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - auth
  /auth/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Me
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign up
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.SignUpIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.TokenOut'
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign up
      tags:
      - auth
  /channels/{channel_id}/members/search:
    get:
      parameters:
      - description: Channel ID (UUID)
        in: path
        name: channel_id
        required: true
        type: string
      - description: query string (part of email or display_name)
        in: query
        name: q
        required: true
        type: string
      - description: limit (max 50, default 20)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http_handlers.MemberCandidateRow'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Search members of the workspace which the channel belongs to (exclude
        current channel members)
      tags:
      - channels
  /channels/{channel_id}/messages:
    get:
      parameters:
      - description: Channel ID (UUID)
        in: path
        name: channel_id
        required: true
        type: string
      - description: If set, returns replies under the thread root
        in: query
        name: thread_root_id
        type: string
      - description: If true, returns only top-level messages
        in: query
        name: root_only
        type: boolean
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http_handlers.MsgOut'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: List messages (channel timeline or thread replies)
      tags:
      - messages
    post:
      consumes:
      - application/json
      parameters:
      - description: Channel ID (UUID)
        in: path
        name: channel_id
        required: true
        type: string
      - description: message
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.MsgCreateIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.MsgOut'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create message (supports thread replies)
      tags:
      - messages
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Health check
      tags:
      - health
  /users/search:
    get:
      parameters:
      - description: query string (part of email or display_name)
        in: query
        name: q
        required: true
        type: string
      - description: limit (max 50, default 20)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http_handlers.UserRow'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Search registered users (email/display_name contains q)
      tags:
      - users
  /workspaces:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/slackgo_internal_model.Workspace'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: List my workspaces
      tags:
      - workspaces
    post:
      consumes:
      - application/json
      parameters:
      - description: workspace payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.CreateWorkspaceIn'
      produces:
      - application/json
      responses:
        "200":
          description: 'id: UUID string'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create workspace
      tags:
      - workspaces
  /workspaces/{ws_id}/channels:
    get:
      parameters:
      - description: Workspace ID (UUID)
        in: path
        name: ws_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: List channels visible in a workspace
      tags:
      - channels
    post:
      consumes:
      - application/json
      parameters:
      - description: Workspace ID (UUID)
        in: path
        name: ws_id
        required: true
        type: string
      - description: channel payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.CreateChannelIn'
      produces:
      - application/json
      responses:
        "200":
          description: 'id: UUID string'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create channel
      tags:
      - channels
  /workspaces/{ws_id}/members:
    get:
      parameters:
      - description: Workspace ID (UUID)
        in: path
        name: ws_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http_handlers.WorkspaceMemberRow'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: List workspace members
      tags:
      - workspaces
    post:
      consumes:
      - application/json
      parameters:
      - description: Workspace ID (UUID)
        in: path
        name: ws_id
        required: true
        type: string
      - description: member payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.AddWorkspaceMemberIn'
      produces:
      - application/json
      responses:
        "200":
          description: 'ok: true'
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Add member to workspace
      tags:
      - workspaces
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
